using NpgsqlTypes;

namespace TwitchBot.Main.Enums
{
	public enum Scope
	{
		[PgName("AnalyticsReadExtensions")] AnalyticsReadExtensions,
		[PgName("AnalyticsReadGames")] AnalyticsReadGames,
		[PgName("BitsRead")] BitsRead,
		[PgName("ChannelEditCommercial")] ChannelEditCommercial,
		[PgName("ChannelManageBroadcast")] ChannelManageBroadcast,
		[PgName("ChannelManageExtensions")] ChannelManageExtensions,
		[PgName("ChannelManagePolls")] ChannelManagePolls,
		[PgName("ChannelManagePredictions")] ChannelManagePredictions,
		[PgName("ChannelManageRedemptions")] ChannelManageRedemptions,
		[PgName("ChannelManageSchedule")] ChannelManageSchedule,
		[PgName("ChannelManageVideos")] ChannelManageVideos,
		[PgName("ChannelReadEditors")] ChannelReadEditors,
		[PgName("ChannelReadGoals")] ChannelReadGoals,
		[PgName("ChannelReadHype_train")] ChannelReadHype_train,
		[PgName("ChannelReadPolls")] ChannelReadPolls,
		[PgName("ChannelReadPredictions")] ChannelReadPredictions,
		[PgName("ChannelReadRedemptions")] ChannelReadRedemptions,
		[PgName("ChannelReadStream_key")] ChannelReadStream_key,
		[PgName("ChannelReadSubscriptions")] ChannelReadSubscriptions,
		[PgName("ClipsEdit")] ClipsEdit,
		[PgName("ModerationRead")] ModerationRead,
		[PgName("ModeratorManageBanned_users")] ModeratorManageBanned_users,
		[PgName("ModeratorReadBlocked_terms")] ModeratorReadBlocked_terms,
		[PgName("ModeratorManageBlocked_terms")] ModeratorManageBlocked_terms,
		[PgName("ModeratorManageAutomod")] ModeratorManageAutomod,
		[PgName("ModeratorReadAutomod_settings")] ModeratorReadAutomod_settings,
		[PgName("ModeratorManageAutomod_settings")] ModeratorManageAutomod_settings,
		[PgName("ModeratorReadChat_settings")] ModeratorReadChat_settings,
		[PgName("ModeratorManageChat_settings")] ModeratorManageChat_settings,
		[PgName("UserEdit")] UserEdit,
		[PgName("UserEditFollows")] UserEditFollows,
		[PgName("UserManageBlocked_users")] UserManageBlocked_users,
		[PgName("UserReadBlocked_users")] UserReadBlocked_users,
		[PgName("UserReadBroadcast")] UserReadBroadcast,
		[PgName("UserReadEmail")] UserReadEmail,
		[PgName("UserReadFollows")] UserReadFollows,
		[PgName("UserReadSubscription")] UserReadSubscription,
	}
}