using NpgsqlTypes;

namespace TwitchBot.Main.Enums
{
	public enum Scope
	{
		[PgName("analytics:read:extensions")] AnalyticsReadExtensions,
		[PgName("analytics:read:games")] AnalyticsReadGames,
		[PgName("bits:read")] BitsRead,
		[PgName("channel:edit:commercial")] ChannelEditCommercial,
		[PgName("channel:manage:broadcast")] ChannelManageBroadcast,
		[PgName("channel:manage:extensions")] ChannelManageExtensions,
		[PgName("channel:manage:polls")] ChannelManagePolls,
		[PgName("channel:manage:predictions")] ChannelManagePredictions,
		[PgName("channel:manage:redemptions")] ChannelManageRedemptions,
		[PgName("channel:manage:schedule")] ChannelManageSchedule,
		[PgName("channel:manage:videos")] ChannelManageVideos,
		[PgName("channel:read:editors")] ChannelReadEditors,
		[PgName("channel:read:goals")] ChannelReadGoals,
		[PgName("channel:read:hype_train")] ChannelReadHype_train,
		[PgName("channel:read:polls")] ChannelReadPolls,
		[PgName("channel:read:predictions")] ChannelReadPredictions,
		[PgName("channel:read:redemptions")] ChannelReadRedemptions,
		[PgName("channel:read:stream_key")] ChannelReadStream_key,
		[PgName("channel:read:subscriptions")] ChannelReadSubscriptions,
		[PgName("clips:edit")] ClipsEdit,
		[PgName("moderation:read")] ModerationRead,
		[PgName("moderator:manage:banned_users")] ModeratorManageBanned_users,
		[PgName("moderator:read:blocked_terms")] ModeratorReadBlocked_terms,
		[PgName("moderator:manage:blocked_terms")] ModeratorManageBlocked_terms,
		[PgName("moderator:manage:automod")] ModeratorManageAutomod,
		[PgName("moderator:read:automod_settings")] ModeratorReadAutomod_settings,
		[PgName("moderator:manage:automod_settings")] ModeratorManageAutomod_settings,
		[PgName("moderator:read:chat_settings")] ModeratorReadChat_settings,
		[PgName("moderator:manage:chat_settings")] ModeratorManageChat_settings,
		[PgName("user:edit")] UserEdit,
		[PgName("user:edit:follows")] UserEditFollows,
		[PgName("user:manage:blocked_users")] UserManageBlocked_users,
		[PgName("user:read:blocked_users")] UserReadBlocked_users,
		[PgName("user:read:broadcast")] UserReadBroadcast,
		[PgName("user:read:email")] UserReadEmail,
		[PgName("user:read:follows")] UserReadFollows,
		[PgName("user:read:subscriptions")] UserReadSubscriptions,
	}
}